version: "3.9"

services:
  api:
    build: .
    container_name: api-orders-go
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=orders_db
    ports:
      - "5004:5004"
    networks:
      - orders-network

  db:
    image: postgres:16
    container_name: db-orders-go
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders_db
    ports:
      - "5436:5432"
    volumes:
      - dbdata-go:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - orders-network

volumes:
  dbdata-go:

networks:
  orders-network:
    driver: bridge

